parameters:
#    gite_main.example.class: Gite\MainBundle\Example

services:
#    gite_main.example:
#        class: %gite_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
